systems/controllers/QPCommon.cpp: Add missing std namespace for isnan() function.
This commit fixes gcc-4.8 build error on Mac OS X 10.10.4 with
Gurobi 6.0.4 for systems/controllers/QPCommon.cpp:925:30:
error: 'isnan' was not declared in this scope

Signed-off-by: Elvis Dowson <elvis.dowson@gmail.com>