Remove occurrences of unused lambda capture 'this'
Detected by Apple clang (`clang-902.0.39.1`):

```
multibody/rigid_body_plant/rigid_body_plant.cc:1132:18: error: lambda capture 'this' is not used [-Werror,-Wunused-lambda-capture]
  data.L_mult = [this, &limits](const VectorX<T>& w) -> VectorX<T> {
                 ^
bazel-out/darwin-dbg/bin/multibody/rigid_body_plant/_virtual_includes/rigid_body_plant/drake/multibody/rigid_body_plant/rigid_body_plant.h:424:5: note: in instantiation of function template specialization 'drake::systems::RigidBodyPlant<double>::DoCalcDiscreteVariableUpdatesImpl<double>' requested here
    DoCalcDiscreteVariableUpdatesImpl(context, events, updates);
    ^
multibody/rigid_body_plant/rigid_body_plant.cc:1188:18: error: lambda capture 'this' is not used [-Werror,-Wunused-lambda-capture]
  data.G_mult = [this, &G](const VectorX<T>& w) -> VectorX<T> {
                 ^
multibody/rigid_body_plant/rigid_body_plant.cc:1191:28: error: lambda capture 'this' is not used [-Werror,-Wunused-lambda-capture]
  data.G_transpose_mult = [this, &G](const VectorX<T>& lambda) {

multibody/rigid_body_plant/test/compliant_contact_model_test.cc:174:24: error: lambda capture 'this' is not used [-Werror,-Wunused-lambda-capture]
    auto set_params = [this](Element* element, int index) {
```