[examples/pendulum] Include weld joint in Pendulum.urdf (#15426)
* [examples/pendulum] Include weld joint in Pendulum.urdf

The pendulum urdf should *not* be floating by default.  This tripped me up quickly when I was testing something, and I'd like to resolve it now.

This is in some sense an API-breaking change without deprecation.  I don't know how to deprecate the urdf.

Code using the old workflow does get a quite clear error message:
```
RuntimeError: This MultibodyGraph already has a joint 'base_weld' connecting 'WorldBody' to 'base'. Therefore adding joint 'WorldBody_welds_to_base' connecting 'WorldBody' to 'base' is not allowed.
```