Remove unused parameter warnings due to protobuf version in Ubuntu 18.04 (#9161)
Without this commit, error messages such as the one below are visible when compiling
drake with gcc 5 and 6 on Ubuntu 18.04.

error: unused parameter 'deterministic' [-Werror=unused-parameter]
     bool deterministic, ::google::protobuf::uint8* target) const {