got drakeIK to compile again on linux.
NOTE:  I was having a problem initially with linker errors that looked like

../../../lib/libdrakeIK.so: undefined reference to `s_rsfi'
../../../lib/libdrakeIK.so: undefined reference to `i_len'
../../../lib/libdrakeIK.so: undefined reference to `e_wsfi'

but i realized that my PKG_CONFIG_PATH was pointing to the drc build directory (which is old on this virtual machine).
export PKG_CONFIG_PATH=
resolved that for me