Draft: Replace clang.cindex with pygccxml
Begin to replace the clang.cindex usage with pygccxml.

Assumes CastXML is in /usr/local/bin/castxml.
Known errors:
  pygccxml asserts that all include directories exist when run.
  Executing
    bazel build -s --sandbox_debug //tools/workspace/pybind11:generate_sample_header
  returns the following error:
    RuntimeError: include directory("bazel-out/k8-opt/bin/common/_virtual_includes/common") does not exist!