Make DrakeLcmParams an aggregate to fix relevant compilation errors
This type is constructed as an aggregate in drake_lcm.cc

```C++
DrakeLcm::DrakeLcm(std::string lcm_url)
    : DrakeLcm(DrakeLcmParams{.lcm_url = std::move(lcm_url)}) {}
```

```C++
DrakeLcm::DrakeLcm(std::string lcm_url, bool defer_initialization)
    : DrakeLcm(DrakeLcmParams{
          .lcm_url = std::move(lcm_url),
          .channel_suffix = {},
          .defer_initialization = defer_initialization}) {}
```

However, because there are constructors, the type is not
actually an aggregate, causing:

```
drake/lcm/drake_lcm.cc:75:16: error: no matching constructor for initialization of 'drake::lcm::DrakeLcmParams'
    : DrakeLcm(DrakeLcmParams{.lcm_url = std::move(lcm_url)}) {}
               ^             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
drake/lcm/drake_lcm.cc:89:16: error: no matching constructor for initialization of 'drake::lcm::DrakeLcmParams'
    : DrakeLcm(DrakeLcmParams{
               ^             ~
```

MinRepro example:
```C++
struct MyInt
{
    MyInt() = default;
    MyInt(const MyInt&) = default;
    MyInt(MyInt&&) = default;
    MyInt& operator=(const MyInt&) = default;
    MyInt& operator=(MyInt&&) = default;

    int a;
};

int main()
{
    MyInt a{.a = 5}
    (void)a;
    return 0;
}

```

```
error: designated initializers cannot be used with a non-aggregate type ‘MyInt’
   27 |     MyInt a{.a = 5};
      |                   ^
```


Caused by #17337