Remove unused LinearSolver<T>::Solve(const MatrixX<T>&)
gcc-6 reports a warning which we treat as an error:

```
bazel test //solvers/... -c dbg --compiler=gcc-6

ERROR: /home/soonhok/work/drake/solvers/BUILD.bazel:512:1: C++ compilation of rule '//solvers:unrevised_lemke_solver' failed (Exit 1)
solvers/unrevised_lemke_solver.cc:89:17: error: 'drake::MatrixX<T> drake::solvers::{anonymous}::LinearSolver<T>::Solve(drake::MatrixX<T>&) const [with T = double]' defined but not used [-Werror=unused-function]
 MatrixX<double> LinearSolver<double>::Solve(
                 ^~~~~~~~~~~~~~~~~~~~
```