[bazel] Tweak drake_py.bzl for clarity (#17874)
This improves clarity in several sense:

1. Cleans up comments to developers.
2. Changes names to be more suggestive of what the rule is (i.e.,
   "disable_test" actually redirects users, so it is a "redirect_test".
3. Reformats the redirection error message so that the bazel labels are
   easier to see and select.

Without the format change, the message could look like:

ERROR: Please use '//bindings/pydrake/systems:py/planar_scenegraph_visualiz
er_test'; the label '//bindings/pydrake/systems:planar_scenegraph_visualize
r_test' has been removed.

With the change it looks like this:

ERROR: Please use
    //bindings/pydrake/systems:py/planar_scenegraph_visualizer_test
  The label
    //bindings/pydrake/systems:planar_scenegraph_visualizer_test
  does not exist.